### ISSUE TITLE
Components need some docs

### ISSUE THREAD

**Issue by rdrey** [synka/meteor-polymer#1]
Interesting project, thanks! I've been using polymer in meteor, but have been passing in the state from the outside only. I really like the idea of getting the state from polymer components, but the README is a little too brief. I'm sure more others would adopt this package if the docs showed how the collection & query components work.

Thanks!

**Comment by johanholmerin** [comment]
I agree, the meteor components need some documentation. Will write some when I get the time.

In the meanwhile, check out the leaderboard example: https://github.com/synka/meteor-polymer/blob/example/public/components/leaderboard/leaderboard.html

**Comment by johanholmerin** [comment]
@atoy40 has now made a [repo](https://github.com/atoy40/meteor-elements) and written [docs](http://atoy40.github.io/meteor-elements/bower_components/meteor-elements/index.html) for the components.
