### ISSUE TITLE
Migration to new Polymer 1.0

### ISSUE THREAD

**Issue by carlosbkm** [synka/meteor-polymer#3]
Hi,
Since Polymer 1.0 production ready was released last week, are you planning to migrate the code to that version?

**Comment by rohanray** [comment]
Hi,
This looks promising. Even I am interested to know if you have any plans to support polymer 1.0.

**Comment by davidcittadini** [comment]
Same here...

**Comment by johanholmerin** [comment]
Updated.

**Comment by carlosbkm** [comment]
Thanks a lot for updating!

However I'm stuck trying to use your custom meteor components to bind Polymer elements with Meteor data from database. Will you update Leaderboard example to Polymer 1.0 as well?

If you could provide some more documentation on how to use meteor components to bind data it would be great.

Thanks in advance, I really appreciate your work.

**Comment by johanholmerin** [comment]
As stated in the readme, the elements are not made by me, but by @atoy40. He has written documentation.

The examples will be updated when I have the time.

**Comment by carlosbkm** [comment]
Ok, thanks a lot for your help!
